apiVersion: apps/v1
kind: Deployment
metadata:
  name: torn-oc-items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torn-oc-items
  template:
    metadata:
      labels:
        app: torn-oc-items
    spec:
      containers:
      - name: oc-item-monitor
        image: localhost:32000/torn-oc-items:0.0.1
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: env-file
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - name: credentials-file
          mountPath: /app/secrets/credentials.json
          subPath: credentials.json
          readOnly: true
      volumes:
      - name: env-file
        secret:
          secretName: torn-secrets
          items:
          - key: .env
            path: .env
      - name: credentials-file
        secret:
          secretName: torn-secrets
          items:
          - key: credentials.json
            path: credentials.json